name: CMake Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make Build Directory
      run: apt update && apt install -y wget xz-utils m4 cmake ninja-build build-essential flex bison
    - name: Install Bison
      run: (wget -O /tmp/bison.tar.xz https://ftp.gnu.org/gnu/bison/bison-3.6.tar.xz && tar -xf /tmp/bison.tar.xz -C /tmp && cd /tmp/bison-3.6 && ./configure && make install)
    - name: Install Flex
      run: (wget -O /tmp/flex.tar.gz https://github.com/westes/flex/releases/download/v2.6.3/flex-2.6.3.tar.gz && tar -xf /tmp/flex.tar.gz -C /tmp/ && cd /tmp/flex-2.6.3 && ./configure && make install)
    - name: Make Build Directory
      run: mkdir -p build
    - name: Generate CMake Project
      run: (cd build && cmake ../ -G Ninja)
    - name: Build Project
      run: (cd build && ninja)
    - name: Run Unit-Tests
      run: (cd build && ./source/epoxy_unittests)
